artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/minich-code/datahub/raw/main/Electricity%20Bill%20data%20(1).zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/electricity_bill_dataset.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/electricity_bill_dataset.csv
  numerical_cols:
    - "Refrigerator"
    - "AirConditioner"
    - "Television"
    - "Monitor"
    - "MotorPump"
    - "Month"
    - "MonthlyHours"
    - "TariffRate"

  categorical_cols:
    - "City"
    - "Company"

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts\data_transformation\X_train_transformed.joblib
  test_data_path: artifacts\data_transformation\X_test_transformed.joblib
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/X_test_transformed.joblib
  test_target_variable: artifacts/data_transformation/y_test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json


